### PR TITLE
Compendium folder names, tables and corrections

### PR DESCRIPTION
**Pull request by Cali0n**
Translation of the folder from DnD 5e version 3.1.5 to the best of our knowledge and belief. Translation based on SRD 5.1
In addition, the new equipment packages have been reviewed and missing content has been added.

**Edited JSON files**:
- dnd5e.monsters.json
- dnd5e.items.json
- dnd5e.classfeatures.json
- dnd5e.backgrounds.json
- dnd5e.races.json
- dnd5e.spells.json

I hope these revisions prove useful.

### CODE REVIEW

**Comment by Cali0n** [comment]
"dnd5e.tables.json" (DnD 5e version 3.1.5) has been revised and translated. The translation is based on SRD 5.1.
Based on the tables, a few deviations were noticed in the translation which were adapted in "dnd5e.items.json".

**Comment by Cali0n** [comment]
Update: Correction of the "dnd5e.races.json" breathing weapons have all been translated individually according to a new template. Old translation of damage resistance and breath weapons have been removed as no longer needed.

**Comment by kaikiai** [comment]
Amazing work here. Whats with this Pull Request? Would be amazing if this could be released.

**Review by mhilbrunner — APPROVED** [review]

**Comment by mhilbrunner** [comment]
Released version 3.2.0 with this: https://github.com/mhilbrunner/foundryvtt-dnd5e-lang-de/releases/tag/3.2.0

Please ping me if something breaks, as I'm currently lacking the time for in-depth testing :)

**Pull request merged**
